apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec:
  rbac:
    defaultPolicy: ''
    policy: |
      g, argocdadmins, role:admin
      g, argocdusers, role:user
    scopes: "[groups]"